### ISSUE TITLE
Extended SPI

### ISSUE THREAD

**Issue by Oegtsgeest** [adafruit/Adafruit_FRAM_SPI#2]
As I understand by reading through the CPP there is no provision for the extended SPI library, correct?
How do I work with other SPI hardware with different datamodes?
Note I use a DUE board.

**Comment by microbuilder** [comment]
You'll have to put some logic in there yourself.  SPI with different data modes in kind of a pain, though.  With the same data mode you just need to add a bit of (easy) logic to toggle the CS pin for the device you're talking to (that's what it exists for), but with different modes on the same bus you'll probably need to reinit SPI between transactions.

This is more of a question for the Adafruit support forum, though. Since no one from support monitors questions here, I'm closing this ... but feel free to bring it up over there.
